#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
name: Improvement
title: "[Improvement] "
description: Suggest an improvement on performance, code quality, user experience, etc
labels: [ "improvement" ]
body:

- type: textarea
  attributes:
    label: What would you like to be improved?
    placeholder: >
      Please describe the problem you see and how it is needed to be improved.
  validations:
    required: true

- type: textarea
  attributes:
    label: How should we improve?
    placeholder: >
      Please provide the solution if you have thoughts.
  validations:
    required: false
