package com.digitalpebble.stormcrawler.helper.initialisation;

import com.digitalpebble.stormcrawler.helper.initialisation.base.OpenClassWithAbstractClassAndInterface;

public class ClassInheritingFromOpenClass extends OpenClassWithAbstractClassAndInterface {}
